[http]
  [http.routers]
    [http.routers.http-to-qa-utils]
      rule = "Host(`qa-utils.test`)"
      service = "qa-utils"
      entrypoints = ["http"]
      middlewares = ["redirect"]

    [http.routers.https-to-qa-utils]
      rule = "Host(`qa-utils.test`)"
      service = "qa-utils"
      entrypoints = ["https"]
      [http.routers.https-to-qa-utils.tls]

  [http.services]
    [http.services.qa-utils]
      [http.services.qa-utils.loadBalancer]
       passHostHeader = true

        [[http.services.qa-utils.loadBalancer.servers]]
          url = "http://qa-utils-webapp"

  [http.middlewares]
    [http.middlewares.redirect.redirectScheme]
      scheme = "https"

[tls]
  [[tls.certificates]]
    certFile = "/etc/certs/qa-utils.test+1.pem"
    keyFile = "/etc/certs/qa-utils.test+1-key.pem"
